package com.armavi_bsd.utills

data class LoginJsonObjectKey (
    val responseAgID: String = "ag_id",
    val responseCusID: String = "cus_id",
    val responseAgName: String = "ag_name",
    val responseAgEmail: String = "ag_email",
    val responseAgOfficeAddress: String = "ag_office_address",
    val responseAgMobileNo: String = "ag_mobile_no",
    val responseInactiveDate: String? = "inactive_date",
    val responseMb: String = "mb",
    val responseTaka: String = "taka",
    val responsePreviousDueAmount: String = "previous_due_amount",
    val responseBillCat: String = "bill_cat",
    val responseConnectCharge: String = "connect_charge",
    val responseDeviceType: String? = "device_type",
    val responseFiberColor: String? = "fiber_color",
    val responseFiberLatency: String? = "fiber_latency",
    val responseSpilterType: String? = "spilter_type",
    val responseLongParameter: String? = "long_parameter",
    val responseHouse: String? = "house",
    val responseRoad: String? = "road",
    val responseZone: String = "zone",
    val responseBillingPersonID: String = "billing_person_id",
    val responseZoneName: String = "zone_name",
    val responseThana: String? = "thana",
    val responseIp: String = "ip",
    val responseAgStatus: String = "ag_status",
    val responseMikrotikID: String = "mikrotik_id",
    val responsePayStatus: String = "pay_status",
    val responseDueStatus: String = "due_status",
    val responseBillStatus: String = "bill_status",
    val responseMikrotikDisconnect: String = "mikrotik_disconnect",
    val responseHoldMoneyStatus: String = "hold_money_status",
    val responseBillDate: String = "bill_date",
    val responseDiffMonth: String = "diff_month",
    val responseInDiffMonth: String? = "in_diff_month",
    val responseConnectionDate: String = "connection_date",
    val responseCDate: String = "c_date",
    val responseEntryDate: String = "entry_date"
)