package com.armavi_bsd.utills

data class LoginResponseValues(
    val tempAgId: String = "",
    val tempCusId: String = "",
    val tempAgName: String = "",
    val tempAgEmail: String = "",
    val tempAgOfficeAddress: String = "",
    val tempAgMobileNo: String = "",
    val tempInactiveDate: String? = null,
    val tempMb: String = "",
    val tempTaka: String = "",
    val tempPreviousDueAmount: String = "",
    val tempBillCat: String = "",
    val tempConnectCharge: String = "",
    val tempDeviceType: String? = null,
    val tempFiberColor: String? = null,
    val tempFiberLatency: String? = null,
    val tempSpilterType: String? = null,
    val tempLongParameter: String? = null,
    val tempHouse: String? = null,
    val tempRoad: String? = null,
    val tempZone: String = "",
    val tempBillingPersonId: String = "",
    val tempZoneName: String = "",
    val tempThana: String? = null,
    val tempIp: String = "",
    val tempAgStatus: String = "",
    val tempMikrotikId: String = "",
    val tempPayStatus: String = "",
    val tempDueStatus: String = "",
    val tempBillStatus: String = "",
    val tempMikrotikDisconnect: String = "",
    val tempHoldMoneyStatus: String = "",
    val tempBillDate: String = "",
    val tempDiffMonth: String = "",
    val tempInDiffMonth: String? = null,
    val tempConnectionDate: String = "",
    val tempEntryDate: String = ""
)
