package com.armavi_bsd.utills

data class LoginPrefKey(
    val prefAgId: String = "pref_ag_id",
    val prefCusId: String = "pref_cus_id",
    val prefAgName: String = "pref_ag_name",
    val prefAgEmail: String = "pref_ag_email",
    val prefAgOfficeAddress: String = "pref_ag_office_address",
    val prefAgMobileNo: String = "pref_ag_mobile_no",
    val prefInactiveDate: String = "pref_inactive_date",
    val prefMb: String = "pref_mb",
    val prefTaka: String = "pref_taka",
    val prefPreviousDueAmount: String = "pref_previous_due_amount",
    val prefBillCat: String = "pref_bill_cat",
    val prefConnectCharge: String = "pref_connect_charge",
    val prefDeviceType: String = "pref_device_type",
    val prefFiberColor: String = "pref_fiber_color",
    val prefFiberLatency: String = "pref_fiber_latency",
    val prefSpilterType: String = "pref_spilter_type",
    val prefLongParameter: String = "pref_long_parameter",
    val prefHouse: String = "pref_house",
    val prefRoad: String = "pref_road",
    val prefZone: String = "pref_zone",
    val prefBillingPersonId: String = "pref_billing_person_id",
    val prefZoneName: String = "pref_zone_name",
    val prefThana: String = "pref_thana",
    val prefIp: String = "pref_ip",
    val prefAgStatus: String = "pref_ag_status",
    val prefMikrotikId: String = "pref_mikrotik_id",
    val prefPayStatus: String = "pref_pay_status",
    val prefDueStatus: String = "pref_due_status",
    val prefBillStatus: String = "pref_bill_status",
    val prefMikrotikDisconnect: String = "pref_mikrotik_disconnect",
    val prefHoldMoneyStatus: String = "pref_hold_money_status",
    val prefBillDate: String = "pref_bill_date",
    val prefDiffMonth: String = "pref_diff_month",
    val prefInDiffMonth: String = "pref_in_diff_month",
    val prefConnectionDate: String = "pref_connection_date",
    val prefCDate: String = "pref_c_date",
    val prefEntryDate: String = "pref_entry_date",
    val prefISLoggedIn: String = "ISLOGGEDIN",
    val prefIsRecognition: String = "ISRECOG",
    val prefUserCredential: String = "USER_CREDENTIALS"
)
